version: 2

models:
  - name: dim_users
    description: "User dimension with signup attributes"
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: dim_products
    description: "Product dimension with category hierarchy"
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_campaigns
    description: "Campaign dimension for monetization and activation tracking"
    columns:
      - name: campaign_id
        tests: [not_null, unique]

  - name: fct_orders
    description: "Order fact table (one row per order)"
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: user_id
        tests: [not_null]

  - name: fct_order_items
    description: "Order item fact table (one row per product per order)"
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
